### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by PandoricGalaxy** [Nyxonn/Discord-AIO#16]
![image](https://user-images.githubusercontent.com/86944806/159294497-326e6e52-96ea-4b63-b006-dc979d05131a.png)
![image](https://user-images.githubusercontent.com/86944806/159294594-b65f2e04-0582-4026-854b-de6d78b6cc32.png)
![image](https://user-images.githubusercontent.com/86944806/159294630-940f355d-3369-4041-9860-48ac431f503c.png)
![image](https://user-images.githubusercontent.com/86944806/159294683-901ec432-1ccc-425d-9315-85f1abf5b67a.png)
![image](https://user-images.githubusercontent.com/86944806/159294736-9b9c743e-9e12-4d5e-b143-9939bcfc684c.png)

**Comment by Nyxonn** [comment]
Generate metadata

**Comment by PandoricGalaxy** [comment]
> Generate metadata

How?
