### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by Mewzax** [Nyxonn/Discord-AIO#26]
can i see RAT code ?
i tried but i cant access https://cdn.discordapp.com/attachments/831225076187660348/950038854100983838/DiscordRAT.py
![image](https://user-images.githubusercontent.com/75091300/167690523-23bb7929-8dd2-448a-af72-8cfaa5cf8e75.png)

**Comment by Nyxonn** [comment]
URL has been patched

**Comment by Mewzax** [comment]
ty
