### ISSUE TITLE
any.run

### ISSUE THREAD

**Issue by 1stgen** [Nyxonn/Discord-AIO#32]
https://cdn.discordapp.com/attachments/923343291947290664/989268391929970758/unknown.png
https://cdn.discordapp.com/attachments/923343291947290664/989268450847363072/unknown.png

**Comment by Nyxonn** [comment]
If you are worried about anti-virus detections just look up the code and compile it by yourself. It is all open-source skid :)

**Comment by 1stgen** [comment]
xd "open-source skid🤓"
![image](https://user-images.githubusercontent.com/67538556/176949142-58f1fa91-611f-4492-a6f2-a27cdbc62932.png)
