### ISSUE TITLE
[Suggestion] Make forms visible

### ISSUE THREAD

**Issue by save0wastaken** [Nyxonn/Discord-AIO#4]
I can work with the forms and put it in WPF and pretty much make it look better then make a pull request but can you make it to where the forms are visible and not just the main form

**Comment by Nyxonn** [comment]
Just use Visual Studio outline

**Comment by save0wastaken** [comment]
Link?

**Comment by Nyxonn** [comment]
It's an option in Visual Studio

**Comment by save0wastaken** [comment]
I see, thank you! pull request coming soon lol
