### ISSUE TITLE
Bug or idk

### ISSUE THREAD

**Issue by neisyera** [Nyxonn/Discord-AIO#40]
I build the exe file, the webhook checker says that my webhook is valid but when i open my exe that i created it doesnt do anything, the fake error works but nothing else i dont get any info, chrome passwords or anything, help me please, Discord:neisyera_666#5291

**Comment by Zrivx** [comment]
same

**Comment by Pluxoo** [comment]
same

**Comment by Nyxonn** [comment]
Some features needs to be updated, it will be done soon. Sorry for trouble

**Comment by Zrivx** [comment]
> Some features needs to be updated, it will be done soon. Sorry for trouble

ETA ?
