### ISSUE TITLE
discord password Stealer

### ISSUE THREAD

**Issue by Zrivx** [Nyxonn/Discord-AIO#44]
can u add discord password Stealer in 0.7.3 ?

**Comment by Nyxonn** [comment]
I do not think its really possible, but token works just like a password. Although in some cases it needs to be updated. Update soon.

**Comment by Zrivx** [comment]
> I do not think its really possible, but token works just like a password. Although in some cases it needs to be updated. Update soon.
man , i founded loggers be like , qvoid , hs-grabber, piratestealer ,lunar builder, can log password but discord restart requid
