### ISSUE TITLE
Virus or not

### ISSUE THREAD

**Issue by bangbang4** [Nyxonn/Discord-AIO#51]
So i downloaded it and when i wanted to run it Windows warned me that it could be malware or malicious and virustotal detected 55 viruses so is this safe? Please help.

**Comment by Bleed-5468** [comment]
it's safe but it's not working

**Comment by vollehax** [comment]
hello bangbang4. its not virus and its totally safe. i have looked through the whole code and i ve been using it on my real main computer. no problem no worries. 👍👍👍

**Comment by Nyxonn** [comment]
As the people said. Its safe, but it needs to be updated. Will work on it soon :)
