### ISSUE TITLE
Problem z Builderem (tak mysle)     Issue with buillder 

### ISSUE THREAD

**Issue by Future21Future** [Nyxonn/Discord-AIO#55]
Mam problem jak zbuduje już grabbera i uruchomie go na sobie nic sie nie dzieje, probowalem roznych sposob zmienialem nawet webhooki. Webhook spammer działa , a grabber po wlaczeniu nie wysyla zadnych informacji.
I have a problem when I build a grabber and start it on myself, nothing happens, I tried various ways, even changing webhooks. The webhook spammer works and the grabber does not send any information when turned on.

**Comment by Nyxonn** [comment]
Program musi zostać zaktualizowany. Możesz śledzić postępy na naszym telegramie. Niedługo wejdzie w życie aktualizacja.

**Comment by Future21Future** [comment]
> Program musi zostać zaktualizowany. Możesz śledzić postępy na naszym telegramie. Niedługo wejdzie w życie aktualizacja.

Okej  , dziekuje za informacje . Czy bedzie dostepny nowy Discord?
