### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by sudOcrypt** [Nyxonn/Discord-AIO#58]
Is there any support for this? I noticed it does not work thats why I am asking.

**Comment by daniaintgtg** [comment]
bankclipper

**Comment by Nyxonn** [comment]
1. This version needs to be updated, i'm currently working on it in my free time.
2. You can check out our Telegram channel where you will be able to check fresh annoucements.
3. How can it be a clipper if its open-source? gosh skids

**Comment by sudOcrypt** [comment]
> 1. This version needs to be updated, i'm currently working on it in my free time.
> 
> 2. You can check out our Telegram channel where you will be able to check fresh annoucements.
> 
> 3. How can it be a clipper if its open-source? gosh skids

Can I get the telegram link?
