### ISSUE TITLE
Compiler issues

### ISSUE THREAD

**Issue by Real707** [Nyxonn/Discord-AIO#66]
When I build an exe there are a bunch of problems when comp
![image](https://user-images.githubusercontent.com/120487375/219969509-b7e369d9-c7a4-49ed-ad39-cc450653c18f.png)
![image](https://user-images.githubusercontent.com/120487375/219969524-8c07a5a2-7e19-4797-a55b-d4fbdbe65843.png)
![image](https://user-images.githubusercontent.com/120487375/219969549-7170931d-406f-4d1a-8447-66b6b9ade689.png)
![image](https://user-images.githubusercontent.com/120487375/219969563-538791a1-7ae8-4028-9eda-e51a6f29b202.png)

**Comment by Nyxonn** [comment]
Program needs to be updated. Update will be released this year. I'm working on it when i have some free time.

**Comment by Crafedrl25** [comment]
Its still a problem

**Comment by Real707** [comment]
> Program needs to be updated. Update will be released this year. I'm working on it when i have some free time.

Alr thanks
