### ISSUE TITLE
Not sending information to the webhook

### ISSUE THREAD

**Issue by lolbodoo** [Nyxonn/Discord-AIO#67]
i Runed it on my vm but it not sending the information i had the check stuff off for anti vm and i tnot send i tryied on a dummy laptop and its not sending the information

**Comment by lolbodoo** [comment]
And i use a a laptop i dont use anymore and it still did not send the informaton the fake nitro did not work and the other fakes did not work

**Comment by Nyxonn** [comment]
It is because this program needs to be updated. I'm currently working on the update when i have some free time. There is no ETA, but it will be 100% released this year.

**Comment by lolbodoo** [comment]
ok thanks
